# Generated by Django 5.2 on 2025-05-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name_user',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
